name: Keep Render Awake

on:
  schedule:
    - cron: "24 * * * *"   # every hour, 24th minute, all URLs
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: |
          urls=(
            "https://epl-auction-29e8.onrender.com/healthz"
            "https://epl-auction-icw4.onrender.com/healthz"
            "https://epl-auction-fwin.onrender.com/healthz"
            "https://epl-auction-6267.onrender.com/healthz"
            "https://epl-auction-auu4.onrender.com/healthz"
            "https://epl-auction-0stn.onrender.com/healthz"
            "https://epl-auction-vtks.onrender.com/healthz"
            "https://epl-auction-bx2x.onrender.com/healthz"
            "https://epl-auction-z6z4.onrender.com/healthz"
            "https://epl-auction-8agx.onrender.com/healthz"
          )

          for url in "${urls[@]}"; do
            curl -L --fail "$url" || echo "failed: $url"
          done
